# Site settings
title: Lenilson Nascimento
email: me@lnlwd.com
description: > # this means to ignore newlines until "baseurl:"
  An UX Designer and Front end Developer living in Brazil.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lnlwd.com" # the base hostname & protocol for your site
twitter:
  username: thelenilson
github_username:  lnlwd

# Build settings
markdown: kramdown

paginate: 8

exclude:
  - node_modules
  - package.json
  - gulpfile.js

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

collections:
  projects:
    output: false
  talks:
    output: false
  portfolio:
      output: true

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  blanklines: false
  profile: false
  startings: []
