# Site settings
title: Lenilson Nascimento
email: lenilson@lnlwd.com
description: Lenilson Nascimento. Front-end Developer, apaixonado por usabilidade e padrões web.
description_us: Lenilson Nascimento. Front-end Developer, in love by usability and web patterns.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lnlwd.com" # the base hostname & protocol for your site
social_networks:
    - name: "Twitter"
      link: "https://twitter.com/thelenilson"
      img: "twitter.png"
    - name: "Facebook"
      link: "https://www.facebook.com/lnlwd"
      img: "facebook.png"
    - name: "GitHub"
      link: "https://github.com/lnlwd"
      img: "github.png"
    - name: "Linkedin"
      link: "https://br.linkedin.com/pub/lenilson-nascimento/95/723/899"
      img: "linkedin.png"

age: '20'
exp_time: '2'

# Build settings
languages: ["pt_br", "en_us"]
gems:
- jekyll-multiple-languages-plugin
exclude_from_localizations: ["assets"]
markdown: kramdown
css_folder:  '/assets/css'
js_folder:  '/assets/js'
img_folder:  '/assets/img'
sass:
    style: compressed
collections:
    - skills
    - jobs
