# Site settings
title: Lenilson Nascimento
email: me@lnlwd.com
description: > # this means to ignore newlines until "baseurl:"
  An UX Designer and Front end Developer living in Brazil.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lnlwd.com" # the base hostname & protocol for your site
twitter:
  username: thelenilson
github_username:  lnlwd

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

sass:
    style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  blanklines: false
  profile: false
  startings: []
