baseURL = "http://thelenilson.com/"
languageCode = "en-us"
title = "Lenilson Nascimento"
theme = "lnlwd"
disqusShortname = "lnlwd"
staticDir= "static"
[taxonomies]
  tag = "tags"
[blackfriday]
  hrefTargetBlank = true